name: "Test and Lint"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: dev

jobs:
  test:
    name: Test runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install latest NPM
        run: npm i -g npm@latest

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test

  lint:
    needs: test
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run linter
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          continue_on_error: false