name: "Test and Lint"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FIRESTORE_EMULATOR_HOST: ${{ secrets.FIRESTORE_EMULATOR_HOST }}
  FB_SERVICE_ACCOUNT_TYPE: ${{ secrets.FB_SERVICE_ACCOUNT_TYPE }}
  FB_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.FB_SERVICE_ACCOUNT_PROJECT_ID }}
  FB_SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.FB_SERVICE_ACCOUNT_PRIVATE_KEY_ID }}
  FB_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.FB_SERVICE_ACCOUNT_PRIVATE_KEY }}
  FB_SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.FB_SERVICE_ACCOUNT_CLIENT_EMAIL }}
  FB_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.FB_SERVICE_ACCOUNT_CLIENT_ID }}
  FB_SERVICE_ACCOUNT_AUTH_URI: ${{ secrets.FB_SERVICE_ACCOUNT_AUTH_URI }}
  FB_SERVICE_ACCOUNT_TOKEN_URI: ${{ secrets.FB_SERVICE_ACCOUNT_TOKEN_URI }}
  FB_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FB_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL }}
  FB_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL: ${{ secrets.FB_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  TEST_FB_SERVICE_ACCOUNT_TYPE: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_TYPE }}
  TEST_FB_SERVICE_ACCOUNT_PROJECT_ID: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_PROJECT_ID }}
  TEST_FB_SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_PRIVATE_KEY_ID }}
  TEST_FB_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_PRIVATE_KEY }}
  TEST_FB_SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_CLIENT_EMAIL }}
  TEST_FB_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_CLIENT_ID }}
  TEST_FB_SERVICE_ACCOUNT_AUTH_URI: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_AUTH_URI }}
  TEST_FB_SERVICE_ACCOUNT_TOKEN_URI: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_TOKEN_URI }}
  TEST_FB_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_AUTH_PROVIDER_X509_CERT_URL }}
  TEST_FB_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL: ${{ secrets.TEST_FB_SERVICE_ACCOUNT_CLIENT_X509_CERT_URL }}

jobs:
  test:
    name: Test runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install latest NPM
        run: npm i -g npm@latest

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Run tests
        run: npm run firebase-test

  lint:
    needs: test
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run linter
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          continue_on_error: false

  deploy:
    needs: lint
    name: Deploy code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run deploy
        run: npm run deploy